# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuildAutomate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuildAutomate
pod "dsBridge"
pod 'IQKeyboardManagerSwift'
  target 'BuildAutomateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuildAutomateUITests' do
    # Pods for testing
  end

end

target 'NotificationContentExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationContentExtension

end

target 'RichNotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RichNotificationService

end
