#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5.2 effective-4.1.50 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef CORE_SWIFT_H
#define CORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreGraphics;
@import CoreLocation;
@import Flutter;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Core",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC4Core33AvailableCouponFlowViewController")
@interface AvailableCouponFlowViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UITableView;
@class NSNumber;
@class NSIndexPath;
@class UITableViewCell;

@interface AvailableCouponFlowViewController (SWIFT_EXTENSION(Core)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIBarButtonItem;
@class UIEvent;
@class UIButton;
@class UIGestureRecognizer;
@class UITouch;

SWIFT_CLASS("_TtC4Core15CAPSOptionsMenu")
@interface CAPSOptionsMenu : UIView <UIGestureRecognizerDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)barButtonAction:(UIBarButtonItem * _Nonnull)sender event:(UIEvent * _Nonnull)event;
- (void)toggleMenu;
- (void)buttonAction:(UIButton * _Nonnull)sender;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC4Core21CAPSOptionsMenuAction")
@interface CAPSOptionsMenuAction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC4Core21CAPSOptionsMenuButton")
@interface CAPSOptionsMenuButton : UIButton
/// Options Action Initializer
/// \param frame Initial frame of menu button
///
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end


SWIFT_CLASS("_TtC4Core12CAPSPageMenu")
@interface CAPSPageMenu : UIViewController <UIGestureRecognizerDelegate, UIScrollViewDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)shouldAutomaticallyForwardRotationMethods SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



@interface CAPSPageMenu (SWIFT_EXTENSION(Core)) <UIGestureRecognizerDelegate>
@end


@class UIScrollView;

@interface CAPSPageMenu (SWIFT_EXTENSION(Core)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


@interface CAPSPageMenu (SWIFT_EXTENSION(Core))
- (void)viewDidLayoutSubviews;
@end


SWIFT_PROTOCOL("_TtP4Core20CAPSPageMenuDelegate_")
@protocol CAPSPageMenuDelegate
@optional
- (void)willMoveToPage:(UIViewController * _Nonnull)controller index:(NSInteger)index;
- (void)didMoveToPage:(UIViewController * _Nonnull)controller index:(NSInteger)index;
@end


typedef SWIFT_ENUM(NSInteger, CategoryID, closed) {
  CategoryIDRecharge = 1,
  CategoryIDBillpayment = 2,
  CategoryIDFlight = 7,
  CategoryIDCabs = 11,
  CategoryIDGold = 16,
  CategoryIDHotels = 17,
  CategoryIDFastag = 3,
  CategoryIDBus = 18,
  CategoryIDDth = 14,
  CategoryIDDataCard = 15,
  CategoryIDDonations = 19,
  CategoryIDCreditScore = 23,
  CategoryIDGiftCard = 27,
  CategoryIDEvents = 28,
};


SWIFT_CLASS("_TtC4Core17CoreBarButtonItem")
@interface CoreBarButtonItem : UIBarButtonItem
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface CoreBarButtonItem (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable BOOL applyBarButtonTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core10CoreButton")
@interface CoreButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreButton (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable NSInteger buttonDisplayType;
@property (nonatomic) IBInspectable BOOL applyTextColorTheme;
@property (nonatomic) IBInspectable BOOL applyBackgroundColorTheme;
@property (nonatomic) IBInspectable BOOL applyImageTintTheme;
@property (nonatomic) IBInspectable BOOL applyBackgroundImageTintTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core16CoreImageUtility")
@interface CoreImageUtility : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC4Core13CoreImageView")
@interface CoreImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreImageView (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyTheme;
@property (nonatomic) IBInspectable BOOL isFlippable;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core14CoreInfoButton")
@interface CoreInfoButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreInfoButton (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyImageTintTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core17CoreInfoImageView")
@interface CoreInfoImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreInfoImageView (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyTheme;
@property (nonatomic) IBInspectable BOOL isFlippable;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core9CoreLabel")
@interface CoreLabel : UILabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface CoreLabel (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable NSInteger labelDisplayType;
@property (nonatomic) IBInspectable BOOL applyTextColorTheme;
@property (nonatomic) IBInspectable BOOL applyBackgroundColorTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core24CoreNavigationController")
@interface CoreNavigationController : UINavigationController
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
@end


@interface CoreNavigationController (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable BOOL applyBarTintColorTheme;
@property (nonatomic) IBInspectable BOOL applyTintColorTheme;
@property (nonatomic) IBInspectable BOOL applyTitleColorTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core20CorePrimaryImageView")
@interface CorePrimaryImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CorePrimaryImageView (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyTheme;
@property (nonatomic) IBInspectable BOOL isFlippable;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core13CoreSearchBar")
@interface CoreSearchBar : UISearchBar
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface CoreSearchBar (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocPlaceholderKey;
@property (nonatomic) IBInspectable BOOL applySearchBarTheme;
- (void)awakeFromNib;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4Core13CoreTextFiled")
@interface CoreTextFiled : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreTextFiled (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocPlaceholderKey;
@property (nonatomic) IBInspectable NSInteger textFieldDisplayType;
@property (nonatomic) IBInspectable BOOL applyTextFieldColorTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core20CouponViewController")
@interface CouponViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@interface CouponViewController (SWIFT_EXTENSION(Core)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end



@interface CouponViewController (SWIFT_EXTENSION(Core)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


/// A class for displaying a vertical scrolling calendar view. Supports selecting a range of dates and dragging those days around
SWIFT_CLASS("_TtC4Core14DTCalendarView")
@interface DTCalendarView : UIView
/// Create a new calendar view with the default start/end dates
///
/// returns:
/// a new calendar view
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



@interface DTCalendarView (SWIFT_EXTENSION(Core)) <UIGestureRecognizerDelegate>
/// This ensures that a selected date (start or end) gets the pan if on it
/// But the scrollview gets it other wise
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionView;
@class UICollectionViewCell;

@interface DTCalendarView (SWIFT_EXTENSION(Core)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=6.0);
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=6.0);
@end

@class UICollectionViewLayout;

@interface DTCalendarView (SWIFT_EXTENSION(Core)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
@end


typedef SWIFT_ENUM(NSInteger, DeeplinkType, closed) {
  DeeplinkTypeCabs = 0,
  DeeplinkTypeHotel = 1,
  DeeplinkTypeEvents = 2,
  DeeplinkTypeFood = 3,
  DeeplinkTypeRecharge = 4,
  DeeplinkTypeRechargeMobile = 5,
  DeeplinkTypeRechargeDth = 6,
  DeeplinkTypeRechargeDatacard = 7,
  DeeplinkTypeBillPayment = 8,
  DeeplinkTypeDeals = 9,
  DeeplinkTypeDonations = 10,
  DeeplinkTypeDonationTransactions = 11,
  DeeplinkTypeDonationCustomerSupport = 12,
  DeeplinkTypeHotelOrderReview = 13,
  DeeplinkTypeFlightsOrderReview = 14,
  DeeplinkTypeCabsOrderReview = 15,
  DeeplinkTypeDonationsTransactions = 16,
  DeeplinkTypeDonationCauseDetails = 17,
  DeeplinkTypeOfflineDeals = 18,
  DeeplinkTypeOnlineDeals = 19,
  DeeplinkTypeAccount = 20,
  DeeplinkTypeConnectedAccount = 21,
  DeeplinkTypeHoroscope = 22,
  DeeplinkTypeCustomerSupportWriteToUs = 23,
  DeeplinkTypeCustomerSupportCategory = 24,
  DeeplinkTypeCustomerSupportOrder = 25,
  DeeplinkTypeMyTransactions = 26,
  DeeplinkTypeRechargeTransactions = 27,
  DeeplinkTypeBillpaymentsTransactions = 28,
  DeeplinkTypeFlights = 29,
  DeeplinkTypeCabsListing = 30,
  DeeplinkTypeBus = 31,
  DeeplinkTypeRechargeCustomerSupport = 32,
  DeeplinkTypeBillPaymentCustomerSupport = 33,
  DeeplinkTypeFoodCustomerSupport = 34,
  DeeplinkTypeCabCustomerSupport = 35,
  DeeplinkTypeDealsCustomerSupport = 36,
  DeeplinkTypeFlightsCustomerSupport = 37,
  DeeplinkTypeGoldCustomerSupport = 38,
  DeeplinkTypeHotelCustomerSupport = 39,
  DeeplinkTypeBusCustomerSupport = 40,
  DeeplinkTypeExplore = 41,
  DeeplinkTypeOrderDetails = 42,
  DeeplinkTypeGold = 43,
  DeeplinkTypeGoldDeliverScreen = 44,
  DeeplinkTypeGoldBuyScreen = 45,
  DeeplinkTypeRechargeOrderReview = 46,
  DeeplinkTypeBillPaymentReviewbill = 47,
  DeeplinkTypeExternalService = 48,
  DeeplinkTypeExternalCommon = 49,
  DeeplinkTypeCustomerSupport = 50,
  DeeplinkTypeFlightTransactions = 51,
  DeeplinkTypeCabsTransactions = 52,
  DeeplinkTypeGoldTransactions = 53,
  DeeplinkTypeHotelTransactions = 54,
  DeeplinkTypeBusTransactions = 55,
  DeeplinkTypeHotelBookingDetail = 56,
  DeeplinkTypeManualLogout = 57,
  DeeplinkTypeFLightsEticket = 58,
  DeeplinkTypeCreditScore = 59,
  DeeplinkTypeCreditScoreTransactions = 60,
  DeeplinkTypeCreditScoreOrderReview = 61,
  DeeplinkTypeCreditScoreReport = 62,
  DeeplinkTypeCreditScoreCustomerSupport = 63,
  DeeplinkTypeCreditScoreClearTop = 64,
  DeeplinkTypeGiftCard = 65,
  DeeplinkTypeGiftCardDetails = 66,
  DeeplinkTypeGiftCardTransactions = 67,
  DeeplinkTypeGiftCardOrderReview = 68,
  DeeplinkTypeGiftCardCustomerSupport = 69,
  DeeplinkTypeGiftCardClearTop = 70,
};

typedef SWIFT_ENUM(NSInteger, EventLogEntryType, closed) {
  EventLogEntryTypeSms = 0,
  EventLogEntryTypePushnotification = 1,
  EventLogEntryTypeDashboard = 2,
  EventLogEntryTypeBanner = 3,
};

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("ExploreGridEntity")
@interface ExploreGridEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ExploreGridEntity (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) NSString * _Nullable deepLink;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int32_t id;
@property (nonatomic, copy) NSString * _Nullable description_p;
@property (nonatomic, copy) NSString * _Nullable iconURL;
@property (nonatomic, copy) NSString * _Nullable displayName;
@property (nonatomic) BOOL isBannerActive;
@property (nonatomic, copy) NSString * _Nullable bannerText;
@property (nonatomic, copy) NSString * _Nullable bannerImage;
@end


SWIFT_CLASS("_TtC4Core10InsetLabel")
@interface InsetLabel : UILabel
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IntegrationDestination, closed) {
  IntegrationDestinationNATIVE = 0,
  IntegrationDestinationFLUTTER = 1,
};

typedef SWIFT_ENUM(NSInteger, IntegrationSource, closed) {
  IntegrationSourceNATIVE = 0,
  IntegrationSourcePLUGIN = 1,
};


SWIFT_CLASS("_TtC4Core24JavascriptChannelMethods")
@interface JavascriptChannelMethods : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class CLLocationManager;
@class CLLocation;

SWIFT_CLASS("_TtC4Core15LocationManager")
@interface LocationManager : NSObject <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC4Core12MenuItemView")
@interface MenuItemView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



typedef SWIFT_ENUM(NSInteger, NetworkEnvironment, closed) {
  NetworkEnvironmentPreproduction = 0,
  NetworkEnvironmentProduction = 1,
  NetworkEnvironmentStaging = 2,
  NetworkEnvironmentRegression = 3,
};

@class FlutterEngine;
@class FlutterDartProject;

SWIFT_CLASS("_TtC4Core27NucleiFlutterViewController")
@interface NucleiFlutterViewController : FlutterViewController
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithEngine:(FlutterEngine * _Nonnull)engine nibName:(NSString * _Nullable)nibName bundle:(NSBundle * _Nullable)nibBundle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithProject:(FlutterDartProject * _Nullable)project nibName:(NSString * _Nullable)nibName bundle:(NSBundle * _Nullable)nibBundle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithProject:(FlutterDartProject * _Nullable)project initialRoute:(NSString * _Nullable)initialRoute nibName:(NSString * _Nullable)nibName bundle:(NSBundle * _Nullable)nibBundle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP4Core23ParterClevertapNotifier_")
@protocol ParterClevertapNotifier
- (void)trackClevertapEventsWithEventName:(NSString * _Nonnull)eventName props:(NSDictionary * _Nonnull)props;
@end


SWIFT_CLASS("_TtC4Core23PartnerAnalyticsTracker")
@interface PartnerAnalyticsTracker : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4Core13PoweredByView")
@interface PoweredByView : UIView
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PreferredLocalization, closed) {
  PreferredLocalizationDefault = 0,
  PreferredLocalizationEnglish = 1,
  PreferredLocalizationArabic = 2,
};

typedef SWIFT_ENUM(NSInteger, PresentationStyle, closed) {
  PresentationStyleDefault = 0,
  PresentationStyleFullscreen = 1,
};

typedef SWIFT_ENUM(NSInteger, RNActivityIndicatorAlignment, closed) {
  RNActivityIndicatorAlignmentLeft = 0,
  RNActivityIndicatorAlignmentCenter = 1,
  RNActivityIndicatorAlignmentRight = 2,
};


SWIFT_CLASS("_TtC4Core15RNLoadingButton")
@interface RNLoadingButton : CoreButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)setTitle:(NSString * _Null_unspecified)title forState:(UIControlState)state;
- (NSString * _Nullable)titleForState:(UIControlState)state SWIFT_WARN_UNUSED_RESULT;
- (void)setImage:(UIImage * _Null_unspecified)image forState:(UIControlState)state;
- (UIImage * _Nullable)imageForState:(UIControlState)state SWIFT_WARN_UNUSED_RESULT;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface UIApplication (SWIFT_EXTENSION(Core)) <UIGestureRecognizerDelegate>
- (void)addGesture;
- (void)removeGesture;
@end


@interface UIBarButtonItem (SWIFT_EXTENSION(Core))
- (void)didTapButtonWithSender:(id _Nonnull)sender;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC4Core10UICheckBox")
@interface UICheckBox : UIButton
@property (nonatomic, getter=isSelected) BOOL selected;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end











@interface UINavigationController (SWIFT_EXTENSION(Core))
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@end





@class NSTimer;
@class UITapGestureRecognizer;

@interface UIView (SWIFT_EXTENSION(Core))
- (void)toastTimerDidFinish:(NSTimer * _Nonnull)timer;
- (void)handleToastTapped:(UITapGestureRecognizer * _Nonnull)recognizer;
@end






SWIFT_CLASS("_TtC4Core17UserLoginMetaData")
@interface UserLoginMetaData : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, NSNumber *> * _Nonnull registeredModes;
@property (nonatomic, copy) NSString * _Nonnull currentProfileMode;
- (nonnull instancetype)initWithRegisteredModes:(NSDictionary<NSString *, NSNumber *> * _Nonnull)registeredModes currentProfileMode:(NSString * _Nonnull)currentProfileMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC4Core19WalletTableViewCell")
@interface WalletTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.5.2 effective-4.1.50 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef CORE_SWIFT_H
#define CORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreGraphics;
@import CoreLocation;
@import Flutter;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Core",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC4Core33AvailableCouponFlowViewController")
@interface AvailableCouponFlowViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UITableView;
@class NSNumber;
@class NSIndexPath;
@class UITableViewCell;

@interface AvailableCouponFlowViewController (SWIFT_EXTENSION(Core)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIBarButtonItem;
@class UIEvent;
@class UIButton;
@class UIGestureRecognizer;
@class UITouch;

SWIFT_CLASS("_TtC4Core15CAPSOptionsMenu")
@interface CAPSOptionsMenu : UIView <UIGestureRecognizerDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)barButtonAction:(UIBarButtonItem * _Nonnull)sender event:(UIEvent * _Nonnull)event;
- (void)toggleMenu;
- (void)buttonAction:(UIButton * _Nonnull)sender;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC4Core21CAPSOptionsMenuAction")
@interface CAPSOptionsMenuAction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC4Core21CAPSOptionsMenuButton")
@interface CAPSOptionsMenuButton : UIButton
/// Options Action Initializer
/// \param frame Initial frame of menu button
///
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end


SWIFT_CLASS("_TtC4Core12CAPSPageMenu")
@interface CAPSPageMenu : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface CAPSPageMenu (SWIFT_EXTENSION(Core)) <UIGestureRecognizerDelegate>
@end


@class UIScrollView;

@interface CAPSPageMenu (SWIFT_EXTENSION(Core)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


@interface CAPSPageMenu (SWIFT_EXTENSION(Core))
- (void)viewDidLayoutSubviews;
@end


SWIFT_PROTOCOL("_TtP4Core20CAPSPageMenuDelegate_")
@protocol CAPSPageMenuDelegate
@optional
- (void)willMoveToPage:(UIViewController * _Nonnull)controller index:(NSInteger)index;
- (void)didMoveToPage:(UIViewController * _Nonnull)controller index:(NSInteger)index;
@end


typedef SWIFT_ENUM(NSInteger, CategoryID, closed) {
  CategoryIDRecharge = 1,
  CategoryIDBillpayment = 2,
  CategoryIDFlight = 7,
  CategoryIDCabs = 11,
  CategoryIDGold = 16,
  CategoryIDHotels = 17,
  CategoryIDFastag = 3,
  CategoryIDBus = 18,
  CategoryIDDth = 14,
  CategoryIDDataCard = 15,
  CategoryIDDonations = 19,
  CategoryIDCreditScore = 23,
  CategoryIDGiftCard = 27,
  CategoryIDEvents = 28,
};


SWIFT_CLASS("_TtC4Core17CoreBarButtonItem")
@interface CoreBarButtonItem : UIBarButtonItem
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface CoreBarButtonItem (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable BOOL applyBarButtonTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core10CoreButton")
@interface CoreButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreButton (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable NSInteger buttonDisplayType;
@property (nonatomic) IBInspectable BOOL applyTextColorTheme;
@property (nonatomic) IBInspectable BOOL applyBackgroundColorTheme;
@property (nonatomic) IBInspectable BOOL applyImageTintTheme;
@property (nonatomic) IBInspectable BOOL applyBackgroundImageTintTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core16CoreImageUtility")
@interface CoreImageUtility : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC4Core13CoreImageView")
@interface CoreImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreImageView (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyTheme;
@property (nonatomic) IBInspectable BOOL isFlippable;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core14CoreInfoButton")
@interface CoreInfoButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreInfoButton (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyImageTintTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core17CoreInfoImageView")
@interface CoreInfoImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreInfoImageView (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyTheme;
@property (nonatomic) IBInspectable BOOL isFlippable;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core9CoreLabel")
@interface CoreLabel : UILabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface CoreLabel (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable NSInteger labelDisplayType;
@property (nonatomic) IBInspectable BOOL applyTextColorTheme;
@property (nonatomic) IBInspectable BOOL applyBackgroundColorTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core24CoreNavigationController")
@interface CoreNavigationController : UINavigationController
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
@end


@interface CoreNavigationController (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic) IBInspectable BOOL applyBarTintColorTheme;
@property (nonatomic) IBInspectable BOOL applyTintColorTheme;
@property (nonatomic) IBInspectable BOOL applyTitleColorTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core20CorePrimaryImageView")
@interface CorePrimaryImageView : UIImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CorePrimaryImageView (SWIFT_EXTENSION(Core))
@property (nonatomic) IBInspectable BOOL applyTheme;
@property (nonatomic) IBInspectable BOOL isFlippable;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core13CoreSearchBar")
@interface CoreSearchBar : UISearchBar
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface CoreSearchBar (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocPlaceholderKey;
@property (nonatomic) IBInspectable BOOL applySearchBarTheme;
- (void)awakeFromNib;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4Core13CoreTextFiled")
@interface CoreTextFiled : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CoreTextFiled (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocKey;
@property (nonatomic, copy) IBInspectable NSString * _Nullable xibLocPlaceholderKey;
@property (nonatomic) IBInspectable NSInteger textFieldDisplayType;
@property (nonatomic) IBInspectable BOOL applyTextFieldColorTheme;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC4Core20CouponViewController")
@interface CouponViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@interface CouponViewController (SWIFT_EXTENSION(Core)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end



@interface CouponViewController (SWIFT_EXTENSION(Core)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


/// A class for displaying a vertical scrolling calendar view. Supports selecting a range of dates and dragging those days around
SWIFT_CLASS("_TtC4Core14DTCalendarView")
@interface DTCalendarView : UIView
/// Create a new calendar view with the default start/end dates
///
/// returns:
/// a new calendar view
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



@interface DTCalendarView (SWIFT_EXTENSION(Core)) <UIGestureRecognizerDelegate>
/// This ensures that a selected date (start or end) gets the pan if on it
/// But the scrollview gets it other wise
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionView;
@class UICollectionViewCell;

@interface DTCalendarView (SWIFT_EXTENSION(Core)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=6.0);
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=6.0);
@end

@class UICollectionViewLayout;

@interface DTCalendarView (SWIFT_EXTENSION(Core)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
@end


typedef SWIFT_ENUM(NSInteger, DeeplinkType, closed) {
  DeeplinkTypeCabs = 0,
  DeeplinkTypeHotel = 1,
  DeeplinkTypeEvents = 2,
  DeeplinkTypeFood = 3,
  DeeplinkTypeRecharge = 4,
  DeeplinkTypeRechargeMobile = 5,
  DeeplinkTypeRechargeDth = 6,
  DeeplinkTypeRechargeDatacard = 7,
  DeeplinkTypeBillPayment = 8,
  DeeplinkTypeDeals = 9,
  DeeplinkTypeDonations = 10,
  DeeplinkTypeDonationTransactions = 11,
  DeeplinkTypeDonationCustomerSupport = 12,
  DeeplinkTypeHotelOrderReview = 13,
  DeeplinkTypeFlightsOrderReview = 14,
  DeeplinkTypeCabsOrderReview = 15,
  DeeplinkTypeDonationsTransactions = 16,
  DeeplinkTypeDonationCauseDetails = 17,
  DeeplinkTypeOfflineDeals = 18,
  DeeplinkTypeOnlineDeals = 19,
  DeeplinkTypeAccount = 20,
  DeeplinkTypeConnectedAccount = 21,
  DeeplinkTypeHoroscope = 22,
  DeeplinkTypeCustomerSupportWriteToUs = 23,
  DeeplinkTypeCustomerSupportCategory = 24,
  DeeplinkTypeCustomerSupportOrder = 25,
  DeeplinkTypeMyTransactions = 26,
  DeeplinkTypeRechargeTransactions = 27,
  DeeplinkTypeBillpaymentsTransactions = 28,
  DeeplinkTypeFlights = 29,
  DeeplinkTypeCabsListing = 30,
  DeeplinkTypeBus = 31,
  DeeplinkTypeRechargeCustomerSupport = 32,
  DeeplinkTypeBillPaymentCustomerSupport = 33,
  DeeplinkTypeFoodCustomerSupport = 34,
  DeeplinkTypeCabCustomerSupport = 35,
  DeeplinkTypeDealsCustomerSupport = 36,
  DeeplinkTypeFlightsCustomerSupport = 37,
  DeeplinkTypeGoldCustomerSupport = 38,
  DeeplinkTypeHotelCustomerSupport = 39,
  DeeplinkTypeBusCustomerSupport = 40,
  DeeplinkTypeExplore = 41,
  DeeplinkTypeOrderDetails = 42,
  DeeplinkTypeGold = 43,
  DeeplinkTypeGoldDeliverScreen = 44,
  DeeplinkTypeGoldBuyScreen = 45,
  DeeplinkTypeRechargeOrderReview = 46,
  DeeplinkTypeBillPaymentReviewbill = 47,
  DeeplinkTypeExternalService = 48,
  DeeplinkTypeExternalCommon = 49,
  DeeplinkTypeCustomerSupport = 50,
  DeeplinkTypeFlightTransactions = 51,
  DeeplinkTypeCabsTransactions = 52,
  DeeplinkTypeGoldTransactions = 53,
  DeeplinkTypeHotelTransactions = 54,
  DeeplinkTypeBusTransactions = 55,
  DeeplinkTypeHotelBookingDetail = 56,
  DeeplinkTypeManualLogout = 57,
  DeeplinkTypeFLightsEticket = 58,
  DeeplinkTypeCreditScore = 59,
  DeeplinkTypeCreditScoreTransactions = 60,
  DeeplinkTypeCreditScoreOrderReview = 61,
  DeeplinkTypeCreditScoreReport = 62,
  DeeplinkTypeCreditScoreCustomerSupport = 63,
  DeeplinkTypeCreditScoreClearTop = 64,
  DeeplinkTypeGiftCard = 65,
  DeeplinkTypeGiftCardDetails = 66,
  DeeplinkTypeGiftCardTransactions = 67,
  DeeplinkTypeGiftCardOrderReview = 68,
  DeeplinkTypeGiftCardCustomerSupport = 69,
  DeeplinkTypeGiftCardClearTop = 70,
};

typedef SWIFT_ENUM(NSInteger, EventLogEntryType, closed) {
  EventLogEntryTypeSms = 0,
  EventLogEntryTypePushnotification = 1,
  EventLogEntryTypeDashboard = 2,
  EventLogEntryTypeBanner = 3,
};

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("ExploreGridEntity")
@interface ExploreGridEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ExploreGridEntity (SWIFT_EXTENSION(Core))
@property (nonatomic, copy) NSString * _Nullable deepLink;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int32_t id;
@property (nonatomic, copy) NSString * _Nullable description_p;
@property (nonatomic, copy) NSString * _Nullable iconURL;
@property (nonatomic, copy) NSString * _Nullable displayName;
@property (nonatomic) BOOL isBannerActive;
@property (nonatomic, copy) NSString * _Nullable bannerText;
@property (nonatomic, copy) NSString * _Nullable bannerImage;
@end


SWIFT_CLASS("_TtC4Core10InsetLabel")
@interface InsetLabel : UILabel
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IntegrationDestination, closed) {
  IntegrationDestinationNATIVE = 0,
  IntegrationDestinationFLUTTER = 1,
};

typedef SWIFT_ENUM(NSInteger, IntegrationSource, closed) {
  IntegrationSourceNATIVE = 0,
  IntegrationSourcePLUGIN = 1,
};


SWIFT_CLASS("_TtC4Core24JavascriptChannelMethods")
@interface JavascriptChannelMethods : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class CLLocationManager;
@class CLLocation;

SWIFT_CLASS("_TtC4Core15LocationManager")
@interface LocationManager : NSObject <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC4Core12MenuItemView")
@interface MenuItemView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



typedef SWIFT_ENUM(NSInteger, NetworkEnvironment, closed) {
  NetworkEnvironmentPreproduction = 0,
  NetworkEnvironmentProduction = 1,
  NetworkEnvironmentStaging = 2,
  NetworkEnvironmentRegression = 3,
};

@class FlutterEngine;
@class FlutterDartProject;

SWIFT_CLASS("_TtC4Core27NucleiFlutterViewController")
@interface NucleiFlutterViewController : FlutterViewController
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithEngine:(FlutterEngine * _Nonnull)engine nibName:(NSString * _Nullable)nibName bundle:(NSBundle * _Nullable)nibBundle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithProject:(FlutterDartProject * _Nullable)project nibName:(NSString * _Nullable)nibName bundle:(NSBundle * _Nullable)nibBundle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithProject:(FlutterDartProject * _Nullable)project initialRoute:(NSString * _Nullable)initialRoute nibName:(NSString * _Nullable)nibName bundle:(NSBundle * _Nullable)nibBundle OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP4Core23ParterClevertapNotifier_")
@protocol ParterClevertapNotifier
- (void)trackClevertapEventsWithEventName:(NSString * _Nonnull)eventName props:(NSDictionary * _Nonnull)props;
@end


SWIFT_CLASS("_TtC4Core23PartnerAnalyticsTracker")
@interface PartnerAnalyticsTracker : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4Core13PoweredByView")
@interface PoweredByView : UIView
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, PreferredLocalization, closed) {
  PreferredLocalizationDefault = 0,
  PreferredLocalizationEnglish = 1,
  PreferredLocalizationArabic = 2,
};

typedef SWIFT_ENUM(NSInteger, PresentationStyle, closed) {
  PresentationStyleDefault = 0,
  PresentationStyleFullscreen = 1,
};

typedef SWIFT_ENUM(NSInteger, RNActivityIndicatorAlignment, closed) {
  RNActivityIndicatorAlignmentLeft = 0,
  RNActivityIndicatorAlignmentCenter = 1,
  RNActivityIndicatorAlignmentRight = 2,
};


SWIFT_CLASS("_TtC4Core15RNLoadingButton")
@interface RNLoadingButton : CoreButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)setTitle:(NSString * _Null_unspecified)title forState:(UIControlState)state;
- (NSString * _Nullable)titleForState:(UIControlState)state SWIFT_WARN_UNUSED_RESULT;
- (void)setImage:(UIImage * _Null_unspecified)image forState:(UIControlState)state;
- (UIImage * _Nullable)imageForState:(UIControlState)state SWIFT_WARN_UNUSED_RESULT;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface UIApplication (SWIFT_EXTENSION(Core)) <UIGestureRecognizerDelegate>
- (void)addGesture;
- (void)removeGesture;
@end


@interface UIBarButtonItem (SWIFT_EXTENSION(Core))
- (void)didTapButtonWithSender:(id _Nonnull)sender;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC4Core10UICheckBox")
@interface UICheckBox : UIButton
@property (nonatomic, getter=isSelected) BOOL selected;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end











@interface UINavigationController (SWIFT_EXTENSION(Core))
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@end





@class NSTimer;
@class UITapGestureRecognizer;

@interface UIView (SWIFT_EXTENSION(Core))
- (void)toastTimerDidFinish:(NSTimer * _Nonnull)timer;
- (void)handleToastTapped:(UITapGestureRecognizer * _Nonnull)recognizer;
@end






SWIFT_CLASS("_TtC4Core17UserLoginMetaData")
@interface UserLoginMetaData : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, NSNumber *> * _Nonnull registeredModes;
@property (nonatomic, copy) NSString * _Nonnull currentProfileMode;
- (nonnull instancetype)initWithRegisteredModes:(NSDictionary<NSString *, NSNumber *> * _Nonnull)registeredModes currentProfileMode:(NSString * _Nonnull)currentProfileMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC4Core19WalletTableViewCell")
@interface WalletTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
